### ISSUE TITLE
Socket IO / Admin Console / Refresh Whose Online

### ISSUE THREAD

**Issue by mtmulch** [mtmulch/mulchronedigital#50]

**Comment by avidtech** [comment]
You're supposed to be sleeping.

**Comment by avidtech** [comment]
I'm gonna take a big look at this shit after Christmas with you if that's
cool.

**Comment by mtmulch** [comment]
I was actually. I posted that way earlier in the night. Just got write it
down sometimes. After Christmas is cool

**Comment by mtmulch** [comment]
This doesn't really add any value to the project overall at this point in time.
