### ISSUE TITLE
Xamarin vs Ionic

### ISSUE THREAD

**Issue by mtmulch** [mtmulch/mulchronedigital#51]
https://ionicframework.com/
https://www.xamarin.com/

**Comment by avidtech** [comment]
Bluntman and chronic?

**Comment by mtmulch** [comment]
Lol 15 bucks little man put that shit in my hand, if that money doesn't
show then...

**Comment by avidtech** [comment]
:D
Xrp trading has given me AIDS

**Comment by mtmulch** [comment]
You need sleep sir.

**Comment by avidtech** [comment]
I've been going to bed at 9pm and waking up at 4.

**Comment by mtmulch** [comment]
https://ionicframework.com/ for sure to keep things consistent. Less content switching on the brain whenever this happens.

**Comment by mtmulch** [comment]
https://github.com/mtmulch/mobile.mulchronedigital
