### ISSUE TITLE
CRON Job for Lets Encrypt Cert renewal

### ISSUE THREAD

**Issue by mtmulch** [mtmulch/mulchronedigital#52]
https://letsencrypt.org

**Comment by avidtech** [comment]
Nice, I'd like to see what parameters they allow, rsa4096 critical would be
nice for some serious opaque piping

**Comment by mtmulch** [comment]
#save10bucksacert

**Comment by mtmulch** [comment]
sudo certbot renew --dry-run with certbot installed.
