### ISSUE TITLE
Home Page Mobile Layout 

### ISSUE THREAD

**Issue by mtmulch** [mtmulch/mulchronedigital#53]
Galaxy S8

**Comment by mtmulch** [comment]
![screenshot_20171227-112814](https://user-images.githubusercontent.com/16274513/34386957-6a03248c-eaf9-11e7-83d2-303add3ae126.png)

**Comment by avidtech** [comment]
Or it's free if I write it too but having an authority is nice.
I just don't like how expensive crit encryption certs are from the big guys
it's like a few k a year.

**Comment by mtmulch** [comment]
No longer relevant.
