### ISSUE TITLE
Generate RSA keypair for each User upon creation.

### ISSUE THREAD

**Issue by mtmulch** [mtmulch/mulchronedigital#56]
For the time being I am going to store these in the user database. Personally I think they should be moved else where in the future. Public key can transfered to user within the JSON webtoken.

All data transferred will be encrypted using symmetric AES, the AES key will then be encrypted with the users unique public RSA key. Only decryptable if the keys match.

Public and private keys will be created upon user creation. Perhaps in the future they should refresh some how to keep them rotating.

**Comment by avidtech** [comment]
What is the bitlength? I'm on my phone
There's a benchmarking thing I need to figure out for this type of shit.
Problem is, there's a fine line with key size to be used, it's more
sensible to use rolling key/hash of shorter length due to
decryption/encryption overhead induced by long RSA.

**Comment by mtmulch** [comment]
2048 for now. Premature optimization is the root of all evil.

**Comment by avidtech** [comment]
Lmao

**Comment by mtmulch** [comment]
https://github.com/mtmulch/mulchronedigital/commit/a6d486af084d492ed6e2ff8cc45d46fb69ec0eda

Updating from RSA2048 to RSA4096 with a double pair of keys makes a noticeable difference on the response time to let the user know their registration was successful. 

Perhaps this can be dispatched to RabbitMQ and passed off to a different service and update the user account entry in the database. I guess by doing that it would require adjustments to the activate account email sent out. User should not be able to activate to their account unless these keys have been generated. Unneeded complexity?

**Comment by mtmulch** [comment]
Will address the performance at a later point in time.
